
version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200"]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: ["5601:5601"]
    depends_on:
      - elasticsearch

  auth-service:
    build: /Users/aamirjamil/Desktop/mern_assignment_fixed/mern_assignment/backend/auth-service
    environment:
      - PORT=4000
      - JWT_SECRET=supersecret
      - MONGO_URI=mongodb+srv://aamirjamil259999:Facebook@123@testing.so85ftf.mongodb.net/?retryWrites=true&w=majority&appName=testing
    ports: ["4000:4000"]
    depends_on:
      - redis
      - elasticsearch

  recommendation-service:
    build: /Users/aamirjamil/Desktop/mern_assignment_fixed/mern_assignment/backend/recommendation-service
    environment:
      - PORT=4001
    ports: ["4001:4001"]

  course-service:
    build: /Users/aamirjamil/Desktop/mern_assignment_fixed/mern_assignment/backend/course-service
    environment:
      - PORT=4002
      - MONGO_URI=mongodb+srv://aamirjamil259999:Facebook@123@testing.so85ftf.mongodb.net/?retryWrites=true&w=majority&appName=testing
      - ELASTICSEARCH_NODE=http://elasticsearch:9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./uploads:/app/uploads
    ports: ["4002:4002"]
    depends_on:
      - redis
      - elasticsearch
